### ISSUE TITLE
Super bonus : ajouter un storybook au front pour documenter tout les nouveaux composants

### ISSUE THREAD

**Issue by DBattou** [BeNextCo/trombenext-frontend#4]
Ce serait royal mais peut être pas pour tout de suite d'ajouter un sotrybook. 
Pour moi ça a plusieurs avantages :  
- Voir un composant isolé (pas besoin de charger toute l'appli pour voir le composant)
- Forcer des bonnes pratiques (developper un composant en isolation permet de le tester sans effet de bord)
- Réutilisation des composants (storybook permet de dev une sorte de banque de composants réutilisables)

**Comment by Alezco** [comment]
PR #13
